def H():
    return 1, 1.0079
def He():
    return 2, 4.0026
def Li():
    return 3, 6.941
def Be():
    return 4, 9.0122
def B():
    return 5, 10.811
def C():
    return 6, 12.0107
def N():
    return 7, 14.0067
def O():
    return 8, 15.9994
def F():
    return 9, 18.9984
def Ne():
    return 10, 20.1797
def Na():
    return 11, 22.9897
def Mg():
    return 12, 24.305
def Al():
    return 13, 26.9815
def Si():
    return 14, 28.0855
def P():
    return 15, 30.9738
def S():
    return 16, 32.065
def Cl():
    return 17, 35.453
def Ar():
    return 18, 39.948
def K():
    return 19, 39.0983
def Ca():
    return 20, 40.078
def Sc():
    return 21, 44.9559
def Ti():
    return 22, 47.867
def V():
    return 23, 50.9415
def Cr():
    return 24, 51.9961
def Mn():
    return 25, 54.938
def Fe():
    return 26, 55.845
def Co():
    return 27, 58.9332
def Ni():
    return 28, 58.6934
def Cu():
    return 29, 63.546
def Zn():
    return 30, 65.39
def Ga():
    return 31, 69.723
def Ge():
    return 32, 72.64
def As():
    return 33, 74.9216
def Se():
    return 34, 78.96
def Br():
    return 35, 79.904
def Kr():
    return 36, 83.8
def Rb():
    return 37, 85.4678
def Sr():
    return 38, 87.62
def Y():
    return 39, 88.9059
def Zr():
    return 40, 91.224
def Nb():
    return 41, 92.9064
def Mo():
    return 42, 95.94
def Tc():
    return 43, 98
def Ru():
    return 44, 101.07
def Rh():
    return 45, 102.9055
def Pd():
    return 46, 106.42
def Ag():
    return 47, 107.8682
def Cd():
    return 48, 112.411
def In():
    return 49, 114.818
def Sn():
    return 50, 118.71
def Sb():
    return 51, 121.76
def Te():
    return 52, 127.6
def I():
    return 53, 126.9045
def Xe():
    return 54, 131.293
def Cs():
    return 55, 132.9055
def Ba():
    return 56, 137.327
def La():
    return 57, 138.9055
def Ce():
    return 58, 140.116
def Pr():
    return 59, 140.9077
def Nd():
    return 60, 144.24
def Pm():
    return 61, 145
def Sm():
    return 62, 150.36
def Eu():
    return 63, 151.964
def Gd():
    return 64, 157.25
def Tb():
    return 65, 158.9253
def Dy():
    return 66, 162.5
def Ho():
    return 67, 164.9303
def Er():
    return 68, 167.259
def Tm():
    return 69, 168.9342
def Ym():
    return 70, 173.04
def Lu():
    return 71, 174.967
def Hf():
    return 72, 178.49
def Ta():
    return 73, 180.9479
def W():
    return 74, 183.84
def Re():
    return 75, 186.207
def Os():
    return 76, 190.23
def Ir():
    return 77, 192.217
def Pt():
    return 78, 195.078
def Au():
    return 79, 196.9665
def Hg():
    return 80, 200.59
def Tl():
    return 81, 204.3833
def Pb():
    return 82, 207.2
def Bi():
    return 83, 208.9804
def Po():
    return 84, 209
def At():
    return 85, 210
def Rn():
    return 86, 222
def Fr():
    return 87, 223
def Ra():
    return 88, 226
def Ac():
    return 89, 227
def Th():
    return 90, 232.0381
def Pa():
    return 91, 231.0359
def U():
    return 92, 238.0289
def Np():
    return 93, 237
def Pu():
    return 94, 244
def Am():
    return 95, 243
def Cm():
    return 96, 247
def Bk():
    return 97, 247
def Cf():
    return 98, 251
def Es():
    return 99, 252
def Fm():
    return 100, 257
def Md():
    return 101, 258
def No():
    return 102, 259
def Lr():
    return 103, 262
def Rf():
    return 104, 261
def Db():
    return 105, 262
def Sg():
    return 106, 266
def Bh():
    return 107, 264
def Hs():
    return 108, 277

print ('References')
print ('1. Atomic Weights of the Elements 2001, Pure Appl. Chem. 75(8), 1107-1122, 2003. Retrieved June 30, 2005. Atomic weights of elements with atomic numbers from 1-109 taken from this source.')
print ('2. IUPAC Standard Atomic Weights Revised (2005).')
print ('3. WebElements Periodic Table. Retrieved June 30, 2005. Atomic weights of elements with atomic numbers 110-116 taken from this source.')
